apiVersion: apps/v1
kind: Deployment
metadata:
  name: thomasscothamilton
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: thomasscothamilton
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: thomasscothamilton
    spec:
      containers:
      - name: thomasscothamilton
        image: thomasscothamilton.azurecr.io/thomasscothamilton/thomasscothamilton:latest
        imagePullPolicy: IfNotPresent
        command:
        - ./manager
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi