# permissions for end users to edit resumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resume-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: thomasscothamilton
    app.kubernetes.io/part-of: thomasscothamilton
    app.kubernetes.io/managed-by: kustomize
  name: resume-editor-role
rules:
- apiGroups:
  - resumes.thomasscothamilton.com
  resources:
  - resumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resumes.thomasscothamilton.com
  resources:
  - resumes/status
  verbs:
  - get
