apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-run-hello
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GoogleCloudPlatform/cloud-run-hello.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: cloud-run-hello
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
