apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openapi-python-flask
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thomasscothamilton/openapi-python-flask.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openapi-python-flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
