apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'        # Official Jetstack Helm repo
    targetRevision: 'v1.12.0'                    # Example version, adjust as needed
    chart: 'cert-manager'
    helm:
      releaseName: 'cert-manager'
      values: |
        # Optionally, override Helm values here
        installCRDs: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true